# -*- coding: utf-8 -*-
"""MiniPoject1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JJ2b5OXGTNdrqaxoxyvaeZrj2HanSpeD
"""

# sentimental analysis of twitter data 
# tweepy library is use to get the twitter api through developer.twitter.com
import tweepy
# textblob library for performing analysis with tweets
from textblob import TextBlob

# this are keys for acessing twitter api 
consumer_key = "Gsy4UGBGblKLS8MHB6R28prFP"
consumer_key_secret = "8x9OS7GLwLa9QUvKQJ6AIvTh6Ajmc34ecE9ptOPWycUZ2l09Ia"

access_token ="1483718735135649795-kf2d1e8hEtbVzcwLEdDSupTFsciycg"
access_token_secret = "Z7zsiiWkU6DVfKXcnOBcf885bMwfg22EIV9mgGM56ZdYM"



# authanticate through OAuthHandler()
auth = tweepy.OAuthHandler(consumer_key,consumer_key_secret)
auth.set_access_token(access_token,access_token_secret)

# establishing connection with twitter
api = tweepy.API(auth)

print(api)

# tweet 
tweet = api.search("hollywood",count = 10)

# # declaring variables for stroring +ve,-ve and neutral tweet

countOfTweet = {
    'positive' : 0,
    'negative' : 0,
    'neutral' : 0
}

# traversing the tweet and print all tweet
for i in tweet:
    print(i.text)

    # TextBlob is use to find polarity and subjectivity of tweet and on the basis of polarity 
    # we can analysis positive ,negative and neutral tweet
    ana = TextBlob(i.text)
    print(ana.sentiment)
    if (ana.sentiment[0] > 0):
        print("Positive ")
        countOfTweet['positive'] = countOfTweet['positive'] + 1
    elif (ana.sentiment[0] < 0):
        print("Negative ")
        countOfTweet['negative'] = countOfTweet['negative'] + 1
    else :
        print("Neutral")
        countOfTweet['neutral'] = countOfTweet['neutral'] + 1

print("number of positive tweet...")
print(countOfTweet['positive'])

print("number of negative tweet...")
print(countOfTweet['negative'])

print("number of neutral tweet...")
print(countOfTweet['neutral'])

import matplotlib.pyplot as plt

# bar chart for tweet
plt.title("Twitter sentiment")
# bar(keys,values,color)
plt.bar(countOfTweet.keys(),countOfTweet.values(),color=['r','g','b'])
plt.show()

plt.title("Twitter sentiment")
# ploting pie chart for tweet
# pi(values,labels,autopct)
plt.pie(countOfTweet.values(),labels=['positive','negative','neutral'],autopct="%1.1f%%")
plt.show()

